# Generated by Django 4.1.3 on 2024-05-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programlar', '0004_remove_program_category_program_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
