# Generated by Django 4.1.3 on 2024-05-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programlar', '0005_alter_program_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='slug',
            field=models.SlugField(blank=True, default='', unique=True),
        ),
    ]
