# Generated by Django 4.1.3 on 2024-05-22 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programlar', '0007_program_category_alter_program_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AlterField(
            model_name='program',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='kurslar', to='programlar.category'),
        ),
        migrations.AlterField(
            model_name='program',
            name='slug',
            field=models.SlugField(blank=True, default='', unique=True),
        ),
    ]
